### PR TITLE
docs: add info about how to enable sequelize plugin

### PR DESCRIPTION
**Pull request by Asher-Tan**
开启sequelize插件

### CODE REVIEW

**Comment by denghongcai** [comment]
thanks for your pr, but how about translate the commit message to english? 

etc. `chore: add info about how to enable sequelize plugin`

**Comment by atian25** [comment]
@denghongcai we use `squash and merge`, so just need to change PR title and modify commit message when merge.

image

**Comment by denghongcai** [comment]
great! I have no permission to merge this pr, so that can't see the dialog you paste. 😢 @atian25

**Comment by atian25** [comment]
@denghongcai now you had.

**Pull request merged**
