### PR TITLE
fix: pkgfiles

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- close https://github.com/eggjs/egg/issues/880

@popomore  `egg-bin ypkgfiles` 不支持 `.sequelizerc` 这个， @huacnlee 这个文件名是必须的么？

### CODE REVIEW

**Comment by popomore** [comment]
放 lib 下？

**Comment by huacnlee** [comment]
`.sequelizerc` 必须的

**Comment by popomore** [comment]
把这个路径纠正下

https://github.com/eggjs/egg-sequelize/blob/master/bin/egg-sequelize

**Comment by atian25** [comment]
@huacnlee 必须这个名字？ 放到 lib 下怎么样？

**Comment by atian25** [comment]
+1

**Pull request merged**
