### PR TITLE
Add a migration example for show up use `co.wrap`.

### PR DESCRIPTION
**Pull request by huacnlee**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by huacnlee** [comment]
合并的时候直接改掉吧，这种没必要再提交了

**Comment by atian25** [comment]
嗯，有记得改就行

**Comment by huacnlee** [comment]
@iyuq 你的例子可以按这种方式调整一下

**Comment by huacnlee** [comment]
你试试一次写多个表，多个 index

**Pull request merged**
